export const FretAttribute = {
  ScaleNote: "ScaleNote",
  ScaleRoot: "ScaleRoot",
  ScaleSecond: "ScaleSecond",
  ScaleThird: "ScaleThird",
  ScaleFourth: "ScaleFourth",
  ScaleFifth: "ScaleFifth",
  ScaleSixth: "ScaleSixth",
  ScaleSeventh: "ScaleSeventh",
  ChordNote: "ChordNote",
  ChordRoot: "ChordRoot",
  ChordSecond: "ChordSecond",
  ChordThird: "ChordThird",
  ChordFourth: "ChordFourth",
  ChordFifth: "ChordFifth",
  ChordSixth: "ChordSixth",
  ChordSeventh: "ChordSeventh",
  NonScale: "NonScale",
  NonScaleHide: "NonScaleHide",
};
